# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"

    config.vm.provision "shell", inline: <<-SHELL
        sudo sed -i "s|http://de.archive.ubuntu.com|http://id.archive.ubuntu.com|g" /etc/apt/sources.list.d/ubuntu.sources
        sudo groupadd portal_admin -g 1001 && sudo useradd -m -s /bin/bash portal_admin -u 1001 -g 1001 && echo "portal_admin:secret123" | sudo chpasswd
        sudo groupadd portal_group
        sudo touch /etc/sudoers.d/00-portal_group && sudo chmod 440 /etc/sudoers.d/00-portal_group
        echo "%portal_group ALL=(ALL) ALL" | sudo tee --append /etc/sudoers.d/00-portal_group
        sudo usermod -a -G portal_group portal_admin
        sudo apt update
        sudo apt upgrade -y
    SHELL

    config.vm.define "ps" do |ps|
        ps.vm.synced_folder ".", "/vagrant", disabled: true
    end
end