# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"

    config.vm.provision "shell", inline: <<-SHELL
        sudo sed -i "s|http://de.archive.ubuntu.com|http://id.archive.ubuntu.com|g" /etc/apt/sources.list.d/ubuntu.sources
        sudo groupadd ws_admin -g 1001 && sudo useradd -m -s /bin/bash ws_admin -u 1001 -g 1001 && echo "ws_admin:secret123" | sudo chpasswd
        sudo groupadd ws_group
        sudo touch /etc/sudoers.d/00-ws_group && sudo chmod 440 /etc/sudoers.d/00-ws_group
        echo "%ws_group ALL=(ALL) ALL" | sudo tee --append /etc/sudoers.d/00-ws_group
        sudo usermod -a -G ws_group ws_admin
        sudo apt update
        sudo apt upgrade -y
    SHELL

    config.vm.define "ws" do |ws|
        ws.vm.synced_folder ".", "/vagrant", disabled: true
    end
end