# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu_24_base"

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"

    config.vm.define "ws" do |ws|
        ws.vm.synced_folder ".", "/vagrant", disabled: true
        ws.vm.provider "libvirt" do |lv|
            lv.memory = 2048
            lv.cpus = 2
        end

        ws.vm.network "private_network", ip: "192.168.58.10"
    end
end